### PR TITLE
fix: HMR reload (resolver side-effects)

### LINKED ISSUE #205: 利用unplugin-auto-import引入组件，在修改文件热更新后进行重载导致样式丢失
### Element Plus version
2.2.5

### OS/Browsers version
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

### unplugin-auto-import version
0.8.7

### Reproduction Link
https://github.com/Pudon/vue3-demo

### Steps to reproduce
1. npm run dev
2. 修改一点代码-热更新
3. 浏览器点击重载
4. 再点击显示消息-样式丢失

### PR DESCRIPTION
**Pull request by azaleta**
fix #205

### CODE REVIEW

File: src/core/resolvers.ts [hunk 1]
```diff
@@ -48,8 +48,13 @@ export function resolversAddon(resolvers: Resolver[]): Addon {
       const dynamic: ImportExtended[] = []
       const sideEffects: ImportExtended[] = []
       await Promise.all([...names].map(async (name) => {
-        if (matched.find(i => i.as === name))
+        const matchedImport = matched.find(i => i.as === name)
+        if (matchedImport) {
+          if (Object.hasOwn(matchedImport, 'sideEffects'))
```
Comment (antfu) [inline src/core/resolvers.ts:53]:
```suggestion
          if ('sideEffects' in matchedImport)
```

`Object.hasOwn` is only available in v16, https://node.green/#ES2022-features-Object-hasOwn

**Comment by antfu** [comment]
Thanks!
